apiVersion: v1
kind: Service
metadata:
  labels:
    app: orchestrator-agent
  name: orchestrator-agent
  namespace: llmops
spec:
  ports:
  - port: 7010
    protocol: TCP
    targetPort: 7010
  selector:
    app: orchestrator-agent