replicaCount: 2


image:
  repository: khanhle04/orchestrator-agent
  tag: v1.0.0
  pullPolicy: IfNotPresent


podAnnotations: {}


resources: {}
  # limits:
  # cpu: 200m
  # memory: 256Mi
  # requests:
  # cpu: 100m
  # memory: 128Mi


affinity: {}
nodeSelector: {}
tolerations: []


service:
  type: NodePort
  port: 80 # Service port (client-facing)
  targetPort: 7010 # Container port app lắng nghe (chỉnh nếu app khác)
  nodePort: 32001 # NodePort cố định


ingress:
  enabled: true
  className: nginx
  annotations: {}
# ví dụ bật rewrite: nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: orchestrator.khanhle.local
      paths:
        - path: /
          pathType: Prefix
  tls:
    enabled: false
    secretName: orchestrator-agent-tls # dùng khi enabled=true


container:
  name: orchestrator-agent
  port: 7010 # trùng với service.targetPort ở trên
  env: [] # ví dụ: [{ name: "ENV", value: "prod" }]
  command: [] # ví dụ: ["/bin/app", "--flag"]
  args: [] # ví dụ: ["--config=/etc/app/config.yaml"]
  livenessProbe:
    enabled: false
  readinessProbe:
    enabled: false