apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: 'https://grafana.github.io/helm-charts'
    chart: grafana
    targetRevision: 23.2.12
    helm:
      releaseName: grafana
      values: |
        ingress:
          enabled: true
          ingressClassName: nginx
          hosts:
            - host: grafana.khanklee.id.vn
              paths:
                - path: /
                  pathType: Prefix
                  servicePort: 3000
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: grafana
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true