apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: 'https://grafana.github.io/helm-charts'
    chart: grafana
    targetRevision: 10.1.4
    helm:
      releaseName: grafana
      values: |
        ingress:
          enabled: true
          ingressClassName: nginx
          path: /
          pathType: Prefix
          hosts:
            - grafana.khanklee.id.vn
      parameters:
        - name: persistence.enabled
          value: "true"

          
          
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: grafana
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true