apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qdrant
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: 'https://qdrant.github.io/qdrant-helm'
    chart: qdrant
    targetRevision: 1.15.5
    helm:
      releaseName: qdrant
      parameters:
        - name: ingress.enabled
          value: "true"
        - name: ingress.ingressClassName
          value: "nginx"
        - name: ingress.hosts[0].host
          value: "qdrant.k8s.master.local"
        - name: ingress.hosts[0].paths[0].servicePort  # ← THÊM DÒNG NÀY
          value: "6333"  # Port của Qdrant service (REST API)
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: qdrant
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true