apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qdrant
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: 'https://qdrant.github.io/qdrant-helm'
    chart: qdrant
    targetRevision: 1.15.5
    helm:
      releaseName: qdrant
      values: |
        ingress:
          enabled: true
          ingressClassName: nginx
          annotations:
            nginx.ingress.kubernetes.io/proxy-body-size: "0"
            nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
            nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
          hosts:
            - host: qdrant.khanklee.id.vn
              paths:
                - path: /
                  pathType: Prefix
                  servicePort: 6333
          
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: qdrant
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true