apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-auth
  namespace: redis
spec:
  encryptedData:
    redis-password: "AgC/sxAeTgjb++I/0tk18cDD/5jREDeCJsaqPGfL5+63PipAI5cFJsZumtmcJQnzbuO3BpZuVtsqYFVLpwwgFQbkvV8S/NtskeOrz9ZXHL3XXTXm1Gia3VfYIprKRmv8yYCTTpA3CjjExij8r6at+qTX+L0farL4vaXbci48XwPbazJdiblKu8YGjx6tq/8LQ+J/KK/MpRyVMubeo5tTYnSKwpwoF+8N3eh3GaJk7USLIXoRS/2ZeN7H+EcKlb8q47aWWLRw0LKy2IajIg5J5ImG8coYzuWu4ivS1GOLuytcQfG2oAMlvWgBwqQUipwMsZN+iPYF7qaVoWF1gvi6cG9XyW9bjqy5VZ4JLrbhrml/ZIpuTnGREnjTUvs9FhhefHPiU0niEJRYcNANJ/Dzpm7V697BU2ZsmgnxaDBxugJRIVtAf6iaMQlaUeFYi2XjWYQ9lu+0EhaiMVzDrVR/112qgTE401a8ADuUEPSRZcv1ywdHHZYoPWYH0MtnJWv5DSZVEPoH4oYTA0SB7BKR8hG1cSo/vK4crxJHEG7DKo5bs4spxHH9omttUX4pBUBhY4HpUq2arrMBcVU7XT88hC5LuIO05hW260j78+xV5trQfmUu7Ub7ylfWDphUYwgXKkyPZAYDj3RE3vUdpH/7r6SO7pBjy5AHUt6waX2xWHkfj8f5avUgWwQy7oovlB+CaSv2RSwFKBlQa00h%"
