apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-auth
  namespace: redis
spec:
  encryptedData:
    redis-password: "AgCB338/20nWh00sIjLel2CF8QlKd1pa2n+jHpDqjUNa9iaSQnPGsV1cbFBxf5wLYAWz7tIxTbya0OBJUa9of2f8pClWWbT1v13egwCtJvWIVDC2se+PivK21dYLwxtQQtJMn9NzEfET+FcmgC1anPdMB4tgUfUXm7mj+5mv9neGfivopFceOcB12sZ1gBIttCuXE8svNn2Bs1jTxQ5310s2NIunNgyvHXXCI1LcSQrKLrfFaWT+EG6ZCUf6H2GVX5MPEnf9gWKXTmCpU++s31McX6wLoy1CchCm70fpd6JOlqEmt89OTB7Siiw9r/zcWCKKj93WO+9kisR+xxD0VsSpBIfcZQwWXu63oE3dNsqMpKrZZ3i4Wkcq6+M4wQmf203l/KycKDNGvUlPhhooE2Kdr8GS2LUVdpnndmWXOOPLBdLwi3FvgyGjPwS65D5AZH4dteR8HUyuWfVGYbbZ2dWZoSaSzoZDdHBDnQb0MH8NXZQBWnv1//bN8B06YwlnVrpAvo/BuH01hVYEODgThPy2QXUybgqIgmEOS+IERLB8e9bmG2RQV4Y3Ulbt9XMli3UQ3ekW2psUpPdG2bxW4+aodQ65gVdcEbqVTC//KcCpjx6R8pfFlCB2KbTfWl4swNnMkdUbC2TfOqVgGkjbV7Cwl0cUvACee4zwiH+u+t6fBuAJh+o2FqSu6ZI5mNx9G7wZwAdPAz3Nzcx/"
  template:
    metadata:
      name: redis-auth
      namespace: redis
    type: Opaque